version: "3.4"

services:
  demo-django-ui:
    build:
      dockerfile: ui.Dockerfile
      context: .
    image: codescope/demo-django-ui:$COMMIT
    ports:
      - "8000:80"
    links:
      - demo-django-frontend

  demo-django-frontend:
    build: .
    image: codescope/demo-django:$COMMIT
    command: ["codescope-run", "gunicorn", "demo.wsgi", "-b", "0.0.0.0:8000"]
    environment:
      - CI
      - CODESCOPE_APIKEY
      - CODESCOPE_API_ENDPOINT
      - CODESCOPE_SERVICE=frontend
      - REDIS_HOST=redis
    links:
      - redis

  demo-django-worker:
    build: .
    image: codescope/demo-django:$COMMIT
    command: ["codescope-run", "celery", "-A", "demo", "worker", "-P", "solo", "-l", "debug"]
    environment:
      - CI
      - CODESCOPE_APIKEY
      - CODESCOPE_API_ENDPOINT
      - CODESCOPE_SERVICE=worker
      - REDIS_HOST=redis
    links:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  tests-worker:
    build: .
    image: codescope/demo-django:$COMMIT
    command: ["codescope-run", "./manage.py", "test", "-p", "tests_worker.py"]
    environment:
      - CI
      - CODESCOPE_APIKEY
      - CODESCOPE_API_ENDPOINT
      - CODESCOPE_SERVICE=worker
      - REDIS_HOST=redis
      - CIRCLECI
      - CIRCLE_BUILD_NUM
      - CIRCLE_BUILD_URL
    links:
      - redis
    depends_on:
      - demo-django-worker

  tests-frontend:
    build: .
    image: codescope/demo-django:$COMMIT
    command: ["codescope-run", "./manage.py", "test", "-p", "tests_frontend.py"]
    environment:
      - CI
      - CODESCOPE_APIKEY
      - CODESCOPE_API_ENDPOINT
      - CODESCOPE_SERVICE=frontend
      - FRONTEND_HOST=demo-django-frontend
      - REDIS_HOST=redis
      - CIRCLECI
      - CIRCLE_BUILD_NUM
      - CIRCLE_BUILD_URL
    links:
      - demo-django-frontend
      - demo-django-worker
