version: "3.4"

services:
  edge:
    image: envoyproxy/envoy:latest
    volumes:
      - "./envoy.yaml:/etc/envoy.yaml:ro"
    command: envoy -c /etc/envoy.yaml
    ports:
      - "8000:80"
    links:
      - frontend
      - ui

  ui:
    image: nginx:latest
    volumes:
      - "./build:/usr/share/nginx/html:ro"

  frontend:
    build: .
    command: ["codescope-run", "gunicorn", "demo.wsgi", "-b", "0.0.0.0:8000"]
    environment:
      - CODESCOPE_APIKEY
      - CODESCOPE_ENVIRONMENT
      - CODESCOPE_API_ENDPOINT
      - CODESCOPE_SERVICE=frontend
      - REDIS_HOST=redis
    links:
     - redis

  worker:
    build: .
    command: ["codescope-run", "celery", "-A", "demo", "worker", "-l", "info"]
    environment:
      - CODESCOPE_APIKEY
      - CODESCOPE_ENVIRONMENT
      - CODESCOPE_API_ENDPOINT
      - CODESCOPE_SERVICE=worker
      - REDIS_HOST=redis
    links:
      - redis

  redis:
    image: redis
