version: "3.4"

services:
  demo-django-ui:
    build:
      dockerfile: ui.Dockerfile
      context: .
    ports:
      - "8000:80"
    links:
      - demo-django-frontend

  demo-django-frontend:
    build: .
    command: ["codescope-run", "gunicorn", "demo.wsgi", "-b", "0.0.0.0:8000"]
    environment:
      - CI
      - CODESCOPE_APIKEY
      - CODESCOPE_ENVIRONMENT
      - CODESCOPE_API_ENDPOINT
      - CODESCOPE_SERVICE=frontend
      - REDIS_HOST=redis
    links:
     - redis

  demo-django-worker:
    build: .
    command: ["codescope-run", "celery", "-A", "demo", "worker", "-l", "info"]
    environment:
      - CI
      - CODESCOPE_APIKEY
      - CODESCOPE_ENVIRONMENT
      - CODESCOPE_API_ENDPOINT
      - CODESCOPE_SERVICE=worker
      - REDIS_HOST=redis
    links:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
