version: "3.4"

services:
  edge:
    image: envoyproxy/envoy:latest
    volumes:
      - "./envoy.yaml:/etc/envoy.yaml:ro"
    command: envoy -c /etc/envoy.yaml
    ports:
      - "8000:80"
    links:
      - api
      - ui

  ui:
    image: nginx:latest
    volumes:
      - "./build:/usr/share/nginx/html:ro"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - CODESCOPE_APIKEY
      - CODESCOPE_ENVIRONMENT
      - CODESCOPE_API_ENDPOINT
      - CODESCOPE_SERVICE=frontend
      - REDIS_HOST=redis
    links:
     - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - CODESCOPE_APIKEY
      - CODESCOPE_ENVIRONMENT
      - CODESCOPE_API_ENDPOINT
      - CODESCOPE_SERVICE=worker
      - REDIS_HOST=redis
    links:
      - redis

  redis:
    image: redis
