version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            codescope-run python -m unittest discover
      - setup_remote_docker
      - run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run: docker build -t codescope/demo-django:$(git rev-parse HEAD) .
      - run: docker push codescope/demo-django:$(git rev-parse HEAD)
      - run: docker build -t codescope/demo-django-ui:$(git rev-parse HEAD) -f ui.Dockerfile .
      - run: docker push codescope/demo-django-ui:$(git rev-parse HEAD)
