version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: COMMIT=$(git rev-parse HEAD) docker-compose build
      - run: COMMIT=$(git rev-parse HEAD) docker-compose up tests-worker
      - run: COMMIT=$(git rev-parse HEAD) docker-compose up tests-frontend
      - run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run: COMMIT=$(git rev-parse HEAD) docker-compose push demo-django-ui demo-django-frontend demo-django-worker
